cabal-version: 3.0
name: sysl
version: 0.1.0.0
license: BSD-3-Clause
license-file: LICENSE
copyright: Tony Day (c) 2026
category: Language
author: Tony Day
maintainer: tonyday567@gmail.com
homepage: https://github.com/tonyday567/sysl#readme
bug-reports: https://github.com/tonyday567/sysl/issues
synopsis: System language interpreter with traced monoidal evaluation
description:
  A system language with commands, values, terms and coterms, interpreted via traced monoidal categories.

build-type: Simple
tested-with:
  ghc ==9.10.1
  ghc ==9.12.2
  ghc ==9.14.1

source-repository head
  type: git
  location: https://github.com/tonyday567/sysl

common ghc-options-stanza
  ghc-options:
    -Wall
    -Wno-unused-imports
    -Wcompat
    -Widentities
    -Wincomplete-record-updates
    -Wincomplete-uni-patterns
    -Wpartial-fields
    -Wredundant-constraints

library
  import: ghc-options-stanza
  default-language: GHC2024
  hs-source-dirs: src
  exposed-modules:
    SysL

  build-depends:
    base >=4.20 && <5,
    circuits >=0.3 && <0.4,
    these >=1.1 && <1.3,

executable sysl-axioma
  import: ghc-options-stanza
  default-language: GHC2024
  main-is: axioma.hs
  hs-source-dirs: app
  build-depends:
    base >=4.20 && <5,
    circuits >=0.3 && <0.4,
    sysl,
    these >=1.1 && <1.3,
